services:
  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    container_name: tournament-db
    volumes:
      - tournament-db:/var/lib/postgresql/data
    ports:
      - "5490:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=secret
    networks:
      - tournament


volumes:
  tournament-db:

networks:
  tournament:
    driver: bridge
    name: tournament